# Generated by Django 2.2.12 on 2020-05-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='MongoDB ID')),
                ('headline', models.CharField(max_length=300, verbose_name='Headline')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('url', models.URLField(null=True, verbose_name='URL')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='Word Count')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('subjectivity', models.DecimalField(decimal_places=25, max_digits=25, verbose_name='Subjectivity')),
                ('polarity', models.DecimalField(decimal_places=25, max_digits=25, verbose_name='Polarity')),
                ('disease', models.CharField(blank=True, max_length=300, null=True, verbose_name='Disease')),
            ],
        ),
    ]
