# Generated by Django 2.2.12 on 2020-05-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='word_count',
        ),
    ]
